# Generated by Django 5.2.7 on 2025-10-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_category_product_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
    ]
